#%RAML 1.0
title: 2291310_test
/listFiles:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [
                {
                  "inboundAttachmentNames": [
                    
                  ],
                  "exceptionPayload": null,
                  "inboundPropertyNames": [
                    
                  ],
                  "outboundAttachmentNames": [
                    
                  ],
                  "payload": "",
                  "outboundPropertyNames": [
                    
                  ],
                  "attributes": {
                    "lastModifiedTime": "2025-07-28T20:53:03.465186",
                    "lastAccessTime": "2025-07-28T20:53:03.465186",
                    "creationTime": "2025-07-28T20:53:03.465186",
                    "symbolicLink": false,
                    "regularFile": true,
                    "directory": false,
                    "path": "C:\\Users\\Downloads\\test\\file-1.txt",
                    "size": 0,
                    "name": "file-1.txt"
                  }
                }
              ]